### ISSUE TITLE
Android 14

### ISSUE THREAD

**Issue by thornos78** [Waterdish/zelda3-android#13]
Hello, I've followed all the instructions precisely, but the application closes when I try to start it. I'm on Android 14; could that be the reason it’s not working?

Any help would be appreciated.
Best regards.

**Comment by Waterdish** [comment]
That may be the reason. How did you get the file to the com.dishii.zelda3 folder?

**Comment by thornos78** [comment]
> That may be the reason. How did you get the file to the com.dishii.zelda3 folder?

I'm using the same file that I used to play on the Nintendo Switch, it worked without problems there, but unfortunately I no longer have that console.

**Comment by Waterdish** [comment]
Did you move the file with a file Explorer on your phone, or a connection to your computer?

**Comment by thornos78** [comment]
connection to my computer

**Comment by thornos78** [comment]
> Did you move the file with a file Explorer on your phone, or a connection to your computer?

Connection to my computer.

**Comment by Waterdish** [comment]
Try regenerating the zelda3_assets.dat file on your computer and transferring it again. If the one from your switch was from before August 2023, it's probably outdated.

**Comment by thornos78** [comment]
> Try regenerating the zelda3_assets.dat file on your computer and transferring it again. If the one from your switch was from before August 2023, it's probably outdated.

Now it worked, thank you very much for the help!

**Comment by Waterdish** [comment]
Have fun!
