### ISSUE TITLE
Crashes on boot.

### ISSUE THREAD

**Issue by djwyman** [Waterdish/zelda3-android#5]
I have tried all 3 versions on my retroid pocket 3+ and installed the zelda3_assets.dat, but still every time I boot it up it crashes.  Here is the crash log if that helps.

` This information is generated from the Crash Log View application. - https://play.google.com/store/apps/details?id=com.arumcomm.crashlogviewer

Process: com.dishii.zelda3
PID: 20574
UID: 10214
Flags: 0x2088be44
Package: com.dishii.zelda3 v1 (1.0.1)
Foreground: Yes
Process-Runtime: 535544
Build: UNISOC/ums512_1h10_Natv/ums512_1h10:11/RP1A.201005.001/21617:user/release-keys

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Native Crash TIME: 1805789
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'UNISOC/ums512_1h10_Natv/ums512_1h10:11/RP1A.201005.001/21617:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-09-13 12:14:08-0500
pid: 20574, tid: 20594, name: RenderThread  >>> com.dishii.zelda3 <<<
uid: 10214
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x18
Cause: null pointer dereference
    x0  0000000000000000  x1  b4000071017279a0  x2  0000000000000538  x3  b400007211780ed0
    x4  b4000070b9744498  x5  0000000000000000  x6  0000000000000001  x7  0000000000000003
    x8  0000000000000000  x9  7c1eea0d8d6ee77b  x10 0000000000000002  x11 0000000000000002
    x12 b400007211781478  x13 0000000000000004  x14 000000000000000e  x15 00000070a37956d8
    x16 00000070a54c9298  x17 00000073551458a0  x18 0000007058f6e000  x19 b400007101727980
    x20 b4000072117841e0  x21 00000070594578b4  x22 b4000072117841e8  x23 b400007101727980
    x24 b400007191751358  x25 0000007059457cc0  x26 0000007059457ff8  x27 00000000000fe000
    x28 00000000000fc000  x29 0000007059457880
    lr  00000070a36b48f4  sp  0000007059457800  pc  00000070a36b48fc  pst 0000000060000000

backtrace:
      #00 pc 00000000007b18fc  /vendor/lib64/egl/libGLES_mali.so (BuildId: a6641c41400ea5ac56e5b6d781ad7ae4)
      #01 pc 00000000007ae710  /vendor/lib64/egl/libGLES_mali.so (eglQuerySurface+868) (BuildId: a6641c41400ea5ac56e5b6d781ad7ae4)
      #02 pc 000000000001da18  /system/lib64/libEGL.so (android::eglQuerySurfaceImpl(void*, void*, int, int*)+252) (BuildId: 745ae29d49a54199bfa0fe5fc115fc20)
      #03 pc 0000000000222390  /system/lib64/libhwui.so (android::uirenderer::renderthread::EglManager::beginFrame(void*)+236) (BuildId: 9fd71167e0b97482d163c6a35375c9af)
      #04 pc 000000000021e46c  /system/lib64/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+404) (BuildId: 9fd71167e0b97482d163c6a35375c9af)
      #05 pc 0000000000220a7c  /system/lib64/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+496) (BuildId: 9fd71167e0b97482d163c6a35375c9af)
      #06 pc 000000000020f2a0  /system/lib64/libhwui.so (android::uirenderer::WorkQueue::process()+220) (BuildId: 9fd71167e0b97482d163c6a35375c9af)
      #07 pc 00000000002302a4  /system/lib64/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+88) (BuildId: 9fd71167e0b97482d163c6a35375c9af)
      #08 pc 0000000000015414  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+260) (BuildId: 4868adbd42643f4c59035cf91f86828c)
      #09 pc 0000000000014cd8  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+412) (BuildId: 4868adbd42643f4c59035cf91f86828c)
      #10 pc 00000000000af97c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: ddedea5a1d1071f97c5321841b6be985)
      #11 pc 00000000000500d0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: ddedea5a1d1071f97c5321841b6be985) `

**Comment by djwyman** [comment]
Never mind My zelda3_assets.dat must have been corrupted because I made a new one, and it now works.

**Comment by Waterdish** [comment]
Glad it works! Let me know if you have any other issues.
